#!/usr/bin/env ruby

message_file = ARGV[0]
message = File.read(message_file)

$grammar_regex = Regexp.new('^[A-Z][^\.]*(?:\.\s[A-Z][^\.]*)*\.$')

if !$grammar_regex.match(message)
  puts "[POLICY] Your message does not match with the English grammar."
  exit 1
end

$github_keywords = '(Related to|Fix|Close)'

$formatting_regex = Regexp.new('^(.(?!'+$github_keywords+'\s{1}#\d+))*(.('+$github_keywords+'\s{1}#\d+))(.(?!'+$github_keywords+'\s{1}#\d+))*$')

if !$formatting_regex.match(message)
  puts "[POLICY] Your message is not formatted correctly."
  exit 1
end